### ISSUE TITLE
A Risk Register write up for sprint 1

### ISSUE THREAD

**Issue by noobling** [noobling/prof-comp#4]

**Comment by m-Dorrell** [comment]
https://www.projectmanager.com/blog/raid-log-use-one

A RAID log might be a good way to get full marks for this part of sprint 1 (going above what other groups would do with minimal extra effort). If you two think it's a good idea, can you email the unit coordinator to ask if it would be a good way to frame the Risk Register?

**Comment by noobling** [comment]
Interesting idea nice way to structure things

**Comment by Brutnip** [comment]
Risk register requires review, especially columns F & G as well as general spellchecking and wording. Columns C & L must be filled with appropriate members. Should columns K & N be kept? If so need to be filled.

**Comment by noobling** [comment]
My opinion:
Risk and response trigger seem similar. Expected impact of response seems a bit difficult to talk about so i would remove.

@Brutnip Are you basically done? You could create a PR so we can review it

**Comment by Brutnip** [comment]
I've done what i can, i agree that they can be removed, the risk owners need to be decided and added, then it just needs to be reviewed. Not sure how to pr

**Comment by Brutnip** [comment]
@noobling Okay cool, thanks for the help. I think I've set it up correctly.

**Comment by m-Dorrell** [comment]
Sprint 1 complete
